/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'from-gray-50',
    'to-gray-100',
    'from-cyan-400',
    'to-blue-500',
    'from-purple-500',
    'to-pink-500',
    'from-cyan-500',
    'to-blue-500',
    'from-red-500',
    'to-pink-500',
    'from-gray-800',
    'to-gray-900',
    'rounded-2xl',
    'rounded-xl',
    'shadow-lg',
    'shadow-sm',
    'shadow-cyan-200',
    'shadow-purple-200',
    'shadow-gray-300',
    'backdrop-blur-lg',
    'bg-white/95',
    'bg-white/20',
    'border-white/30',
    'text-white/80',
    'active:scale-95',
    'duration-200',
    'duration-300',
    'transition-all',
    'transform',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#fdf2f8',
          100: '#fce7f3',
          500: '#ec4899',
          600: '#db2777',
          700: '#be185d',
        },
      },
      fontFamily: {
        'ja': ['Hiragino Kaku Gothic ProN', 'Hiragino Sans', 'Meiryo', 'sans-serif'],
      },
    },
  },
  plugins: [],
}